// LLVM IR Backend for Agnostic Compiler
// Author: AnmiTaliDev <anmitalidev@nuros.org>

use crate::ast::*;
use std::collections::HashMap;

pub struct LLVMIRGenerator {
    body: String,
    label_counter: usize,
    value_counter: usize,
    string_literals: Vec<(String, usize)>, // (content, byte_len_including_null)
    variables: HashMap<String, String>,    // var_name -> alloca ptr register
    block_terminated: bool,
    is_in_main: bool,
}

impl LLVMIRGenerator {
    pub fn new() -> Self {
        LLVMIRGenerator {
            body: String::new(),
            label_counter: 0,
            value_counter: 0,
            string_literals: Vec::new(),
            variables: HashMap::new(),
            block_terminated: false,
            is_in_main: false,
        }
    }

    fn next_label(&mut self) -> String {
        let l = format!("lbl{}", self.label_counter);
        self.label_counter += 1;
        l
    }

    fn next_value(&mut self) -> String {
        let v = format!("%v{}", self.value_counter);
        self.value_counter += 1;
        v
    }

    fn emit_label(&mut self, label: &str) {
        self.body.push_str(&format!("{}:\n", label));
        self.block_terminated = false;
    }

    fn add_string(&mut self, s: &str) -> (usize, usize) {
        for (i, (existing, len)) in self.string_literals.iter().enumerate() {
            if existing == s {
                return (i, *len);
            }
        }
        let len = string_byte_len(s) + 1;
        let idx = self.string_literals.len();
        self.string_literals.push((s.to_string(), len));
        (idx, len)
    }

    pub fn generate(&mut self, program: &Program) -> String {
        // Generate module functions (non-stdio)
        for (mod_name, module) in &program.modules {
            if mod_name == "stdio" {
                continue;
            }
            for func in &module.functions {
                if func.is_exported {
                    self.generate_function(&format!("{}_{}", mod_name, func.name), func);
                }
            }
        }

        // Generate stdlib stdio wrapper functions
        if program.modules.contains_key("stdio") {
            self.generate_stdio();
        }

        // Generate user functions (non-main)
        for func in &program.functions {
            if func.name != "main" {
                self.generate_function(&func.name, func);
            }
        }

        // Generate main
        if let Some(main_func) = program.functions.iter().find(|f| f.name == "main") {
            self.generate_main(main_func);
        }

        // Build final output: header + string globals + body
        let mut out = String::new();

        out.push_str("; Generated by Agnostic Compiler\n");
        out.push_str("; LLVM IR Backend\n");
        out.push_str("; Author: AnmiTaliDev <anmitalidev@nuros.org>\n\n");
        out.push_str("source_filename = \"program.agn\"\n");
        out.push_str("target triple = \"x86_64-pc-linux-gnu\"\n\n");

        // C stdlib declarations
        out.push_str("declare i32 @printf(i8* nocapture readonly, ...)\n");
        out.push_str("declare i32 @scanf(i8* nocapture readonly, ...)\n");
        out.push_str("declare i32 @putchar(i32)\n");
        out.push_str("declare i32 @getchar()\n");
        out.push_str("declare i64 @strlen(i8*)\n");
        out.push_str("declare i8* @strcat(i8*, i8* readonly)\n");
        out.push_str("declare i8* @sprintf(i8*, i8* readonly, ...)\n");
        out.push_str("declare i8* @fgets(i8*, i32, i8*)\n");
        out.push_str("declare i32 @fflush(i8*)\n");
        out.push_str("declare void @exit(i32)\n");
        out.push_str("@stdin = external global i8*\n\n");

        // Global string constants
        for (i, (s, len)) in self.string_literals.iter().enumerate() {
            let escaped = llvm_escape(s);
            out.push_str(&format!(
                "@.str.{} = private unnamed_addr constant [{} x i8] c\"{}\\00\", align 1\n",
                i, len, escaped
            ));
        }
        if !self.string_literals.is_empty() {
            out.push('\n');
        }

        out.push_str(&self.body);
        out
    }

    fn reset_for_function(&mut self) {
        self.variables.clear();
        self.value_counter = 0;
        self.label_counter = 0;
        self.block_terminated = false;
    }

    fn generate_main(&mut self, func: &Function) {
        let saved_vars = self.variables.clone();
        let saved_vc = self.value_counter;
        let saved_lc = self.label_counter;
        let saved_term = self.block_terminated;

        self.reset_for_function();
        self.is_in_main = true;

        self.body.push_str("define i32 @main() {\n");
        self.body.push_str("entry:\n");

        for stmt in &func.body {
            self.generate_statement(stmt);
            if self.block_terminated {
                break;
            }
        }

        if !self.block_terminated {
            self.body.push_str("  ret i32 0\n");
        }
        self.body.push_str("}\n\n");

        self.is_in_main = false;
        self.variables = saved_vars;
        self.value_counter = saved_vc;
        self.label_counter = saved_lc;
        self.block_terminated = saved_term;
    }

    fn generate_function(&mut self, name: &str, func: &Function) {
        let saved_vars = self.variables.clone();
        let saved_vc = self.value_counter;
        let saved_lc = self.label_counter;
        let saved_term = self.block_terminated;

        self.reset_for_function();

        let params: Vec<String> = func
            .params
            .iter()
            .map(|p| format!("i64 %p_{}", p.name))
            .collect();

        self.body
            .push_str(&format!("define i64 @{}({}) {{\n", name, params.join(", ")));
        self.body.push_str("entry:\n");

        for param in &func.params {
            let ptr = format!("%{}", param.name);
            self.body
                .push_str(&format!("  {} = alloca i64, align 8\n", ptr));
            self.body.push_str(&format!(
                "  store i64 %p_{}, i64* {}, align 8\n",
                param.name, ptr
            ));
            self.variables.insert(param.name.clone(), ptr);
        }

        for stmt in &func.body {
            self.generate_statement(stmt);
            if self.block_terminated {
                break;
            }
        }

        if !self.block_terminated {
            self.body.push_str("  ret i64 0\n");
        }
        self.body.push_str("}\n\n");

        self.variables = saved_vars;
        self.value_counter = saved_vc;
        self.label_counter = saved_lc;
        self.block_terminated = saved_term;
    }

    fn generate_statement(&mut self, stmt: &Statement) {
        match stmt {
            Statement::VarDecl {
                name,
                var_type: _,
                value,
            } => {
                let ptr = format!("%var_{}", name);
                self.body
                    .push_str(&format!("  {} = alloca i64, align 8\n", ptr));
                self.variables.insert(name.clone(), ptr.clone());
                if let Some(expr) = value {
                    let val = self.generate_expression(expr);
                    self.body.push_str(&format!(
                        "  store i64 {}, i64* {}, align 8\n",
                        val, ptr
                    ));
                }
            }
            Statement::ArrayDecl {
                name,
                element_type: _,
                size,
            } => {
                let ptr = format!("%arr_{}", name);
                self.body.push_str(&format!(
                    "  {} = alloca i64, i32 {}, align 8\n",
                    ptr, size
                ));
                self.variables.insert(name.clone(), ptr);
            }
            Statement::Assignment { name, value } => {
                let val = self.generate_expression(value);
                if let Some(ptr) = self.variables.get(name).cloned() {
                    self.body.push_str(&format!(
                        "  store i64 {}, i64* {}, align 8\n",
                        val, ptr
                    ));
                }
            }
            Statement::ArrayAssignment { name, index, value } => {
                let val = self.generate_expression(value);
                let idx = self.generate_expression(index);
                if let Some(base_ptr) = self.variables.get(name).cloned() {
                    let elem_ptr = self.next_value();
                    self.body.push_str(&format!(
                        "  {} = getelementptr i64, i64* {}, i64 {}\n",
                        elem_ptr, base_ptr, idx
                    ));
                    self.body.push_str(&format!(
                        "  store i64 {}, i64* {}, align 8\n",
                        val, elem_ptr
                    ));
                }
            }
            Statement::PointerAssignment { target, value } => {
                let val = self.generate_expression(value);
                let ptr_int = self.generate_expression(target);
                let typed_ptr = self.next_value();
                self.body.push_str(&format!(
                    "  {} = inttoptr i64 {} to i64*\n",
                    typed_ptr, ptr_int
                ));
                self.body.push_str(&format!(
                    "  store i64 {}, i64* {}, align 8\n",
                    val, typed_ptr
                ));
            }
            Statement::Return(expr) => {
                if let Some(e) = expr {
                    let val = self.generate_expression(e);
                    if self.is_in_main {
                        let trunc = self.next_value();
                        self.body.push_str(&format!(
                            "  {} = trunc i64 {} to i32\n",
                            trunc, val
                        ));
                        self.body
                            .push_str(&format!("  ret i32 {}\n", trunc));
                    } else {
                        self.body.push_str(&format!("  ret i64 {}\n", val));
                    }
                } else if self.is_in_main {
                    self.body.push_str("  ret i32 0\n");
                } else {
                    self.body.push_str("  ret i64 0\n");
                }
                self.block_terminated = true;
            }
            Statement::Expression(expr) => {
                self.generate_expression(expr);
            }
            Statement::If {
                condition,
                then_body,
                else_body,
            } => {
                let cond_val = self.generate_expression(condition);
                let cond_bool = self.next_value();
                self.body.push_str(&format!(
                    "  {} = icmp ne i64 {}, 0\n",
                    cond_bool, cond_val
                ));

                let then_lbl = self.next_label();
                let else_lbl = self.next_label();
                let end_lbl = self.next_label();

                if else_body.is_some() {
                    self.body.push_str(&format!(
                        "  br i1 {}, label %{}, label %{}\n",
                        cond_bool, then_lbl, else_lbl
                    ));
                } else {
                    self.body.push_str(&format!(
                        "  br i1 {}, label %{}, label %{}\n",
                        cond_bool, then_lbl, end_lbl
                    ));
                }
                self.block_terminated = true;

                self.emit_label(&then_lbl);
                for s in then_body {
                    self.generate_statement(s);
                    if self.block_terminated {
                        break;
                    }
                }
                if !self.block_terminated {
                    self.body
                        .push_str(&format!("  br label %{}\n", end_lbl));
                    self.block_terminated = true;
                }

                if let Some(body) = else_body {
                    self.emit_label(&else_lbl);
                    for s in body {
                        self.generate_statement(s);
                        if self.block_terminated {
                            break;
                        }
                    }
                    if !self.block_terminated {
                        self.body
                            .push_str(&format!("  br label %{}\n", end_lbl));
                        self.block_terminated = true;
                    }
                }

                self.emit_label(&end_lbl);
            }
            Statement::For {
                init: _,
                condition,
                post: _,
                body,
            } => {
                let cond_lbl = self.next_label();
                let body_lbl = self.next_label();
                let end_lbl = self.next_label();

                self.body
                    .push_str(&format!("  br label %{}\n", cond_lbl));
                self.block_terminated = true;

                self.emit_label(&cond_lbl);
                if let Some(cond) = condition {
                    let cond_val = self.generate_expression(cond);
                    let cond_bool = self.next_value();
                    self.body.push_str(&format!(
                        "  {} = icmp ne i64 {}, 0\n",
                        cond_bool, cond_val
                    ));
                    self.body.push_str(&format!(
                        "  br i1 {}, label %{}, label %{}\n",
                        cond_bool, body_lbl, end_lbl
                    ));
                } else {
                    self.body
                        .push_str(&format!("  br label %{}\n", body_lbl));
                }
                self.block_terminated = true;

                self.emit_label(&body_lbl);
                for s in body {
                    self.generate_statement(s);
                    if self.block_terminated {
                        break;
                    }
                }
                if !self.block_terminated {
                    self.body
                        .push_str(&format!("  br label %{}\n", cond_lbl));
                    self.block_terminated = true;
                }

                self.emit_label(&end_lbl);
            }
            Statement::InlineAsm { parts: _ } => {
                // Inline assembly is target-specific and not supported in LLVM IR backend
                self.body
                    .push_str("  ; inline asm not supported in LLVM IR backend\n");
            }
        }
    }

    fn generate_expression(&mut self, expr: &Expression) -> String {
        match expr {
            Expression::Number(n) => format!("{}", n),

            Expression::Identifier(name) => {
                if let Some(ptr) = self.variables.get(name).cloned() {
                    let val = self.next_value();
                    self.body.push_str(&format!(
                        "  {} = load i64, i64* {}, align 8\n",
                        val, ptr
                    ));
                    val
                } else {
                    "0".to_string()
                }
            }

            Expression::Binary { op, left, right } => {
                let lv = self.generate_expression(left);
                let rv = self.generate_expression(right);
                let result = self.next_value();
                match op {
                    BinaryOp::Add => {
                        self.body.push_str(&format!(
                            "  {} = add i64 {}, {}\n",
                            result, lv, rv
                        ));
                    }
                    BinaryOp::Sub => {
                        self.body.push_str(&format!(
                            "  {} = sub i64 {}, {}\n",
                            result, lv, rv
                        ));
                    }
                    BinaryOp::Mul => {
                        self.body.push_str(&format!(
                            "  {} = mul i64 {}, {}\n",
                            result, lv, rv
                        ));
                    }
                    BinaryOp::Div => {
                        self.body.push_str(&format!(
                            "  {} = sdiv i64 {}, {}\n",
                            result, lv, rv
                        ));
                    }
                    BinaryOp::Mod => {
                        self.body.push_str(&format!(
                            "  {} = srem i64 {}, {}\n",
                            result, lv, rv
                        ));
                    }
                    BinaryOp::Equal => {
                        let cmp = self.next_value();
                        self.body.push_str(&format!(
                            "  {} = icmp eq i64 {}, {}\n",
                            cmp, lv, rv
                        ));
                        self.body.push_str(&format!(
                            "  {} = zext i1 {} to i64\n",
                            result, cmp
                        ));
                    }
                    BinaryOp::NotEqual => {
                        let cmp = self.next_value();
                        self.body.push_str(&format!(
                            "  {} = icmp ne i64 {}, {}\n",
                            cmp, lv, rv
                        ));
                        self.body.push_str(&format!(
                            "  {} = zext i1 {} to i64\n",
                            result, cmp
                        ));
                    }
                    BinaryOp::Less => {
                        let cmp = self.next_value();
                        self.body.push_str(&format!(
                            "  {} = icmp slt i64 {}, {}\n",
                            cmp, lv, rv
                        ));
                        self.body.push_str(&format!(
                            "  {} = zext i1 {} to i64\n",
                            result, cmp
                        ));
                    }
                    BinaryOp::LessEqual => {
                        let cmp = self.next_value();
                        self.body.push_str(&format!(
                            "  {} = icmp sle i64 {}, {}\n",
                            cmp, lv, rv
                        ));
                        self.body.push_str(&format!(
                            "  {} = zext i1 {} to i64\n",
                            result, cmp
                        ));
                    }
                    BinaryOp::Greater => {
                        let cmp = self.next_value();
                        self.body.push_str(&format!(
                            "  {} = icmp sgt i64 {}, {}\n",
                            cmp, lv, rv
                        ));
                        self.body.push_str(&format!(
                            "  {} = zext i1 {} to i64\n",
                            result, cmp
                        ));
                    }
                    BinaryOp::GreaterEqual => {
                        let cmp = self.next_value();
                        self.body.push_str(&format!(
                            "  {} = icmp sge i64 {}, {}\n",
                            cmp, lv, rv
                        ));
                        self.body.push_str(&format!(
                            "  {} = zext i1 {} to i64\n",
                            result, cmp
                        ));
                    }
                    BinaryOp::And => {
                        let lb = self.next_value();
                        let rb = self.next_value();
                        let and_r = self.next_value();
                        self.body.push_str(&format!(
                            "  {} = icmp ne i64 {}, 0\n",
                            lb, lv
                        ));
                        self.body.push_str(&format!(
                            "  {} = icmp ne i64 {}, 0\n",
                            rb, rv
                        ));
                        self.body.push_str(&format!(
                            "  {} = and i1 {}, {}\n",
                            and_r, lb, rb
                        ));
                        self.body.push_str(&format!(
                            "  {} = zext i1 {} to i64\n",
                            result, and_r
                        ));
                    }
                    BinaryOp::Or => {
                        let lb = self.next_value();
                        let rb = self.next_value();
                        let or_r = self.next_value();
                        self.body.push_str(&format!(
                            "  {} = icmp ne i64 {}, 0\n",
                            lb, lv
                        ));
                        self.body.push_str(&format!(
                            "  {} = icmp ne i64 {}, 0\n",
                            rb, rv
                        ));
                        self.body.push_str(&format!(
                            "  {} = or i1 {}, {}\n",
                            or_r, lb, rb
                        ));
                        self.body.push_str(&format!(
                            "  {} = zext i1 {} to i64\n",
                            result, or_r
                        ));
                    }
                    BinaryOp::Concat => {
                        // Pass through left value; full concat support requires runtime
                        self.body.push_str(&format!(
                            "  {} = add i64 0, {}\n",
                            result, lv
                        ));
                    }
                    BinaryOp::BitAnd => {
                        self.body.push_str(&format!(
                            "  {} = and i64 {}, {}\n",
                            result, lv, rv
                        ));
                    }
                    BinaryOp::BitOr => {
                        self.body.push_str(&format!(
                            "  {} = or i64 {}, {}\n",
                            result, lv, rv
                        ));
                    }
                    BinaryOp::BitXor => {
                        self.body.push_str(&format!(
                            "  {} = xor i64 {}, {}\n",
                            result, lv, rv
                        ));
                    }
                    BinaryOp::Shl => {
                        self.body.push_str(&format!(
                            "  {} = shl i64 {}, {}\n",
                            result, lv, rv
                        ));
                    }
                    BinaryOp::Shr => {
                        self.body.push_str(&format!(
                            "  {} = ashr i64 {}, {}\n",
                            result, lv, rv
                        ));
                    }
                }
                result
            }

            Expression::Unary { op, operand } => {
                let val = self.generate_expression(operand);
                let result = self.next_value();
                match op {
                    UnaryOp::Neg => {
                        self.body.push_str(&format!(
                            "  {} = sub i64 0, {}\n",
                            result, val
                        ));
                    }
                    UnaryOp::Not => {
                        let cmp = self.next_value();
                        self.body.push_str(&format!(
                            "  {} = icmp eq i64 {}, 0\n",
                            cmp, val
                        ));
                        self.body.push_str(&format!(
                            "  {} = zext i1 {} to i64\n",
                            result, cmp
                        ));
                    }
                }
                result
            }

            Expression::Call { function, args } => {
                let mut arg_strs: Vec<String> = Vec::new();
                for a in args {
                    let v = self.generate_expression(a);
                    arg_strs.push(format!("i64 {}", v));
                }
                let result = self.next_value();
                self.body.push_str(&format!(
                    "  {} = call i64 @{}({})\n",
                    result,
                    function,
                    arg_strs.join(", ")
                ));
                result
            }

            Expression::ModuleCall {
                module,
                function,
                args,
            } => {
                let func_name = format!("{}_{}", module, function);
                let mut arg_strs: Vec<String> = Vec::new();
                for a in args {
                    let v = self.generate_expression(a);
                    arg_strs.push(format!("i64 {}", v));
                }
                let result = self.next_value();
                self.body.push_str(&format!(
                    "  {} = call i64 @{}({})\n",
                    result,
                    func_name,
                    arg_strs.join(", ")
                ));
                result
            }

            Expression::String(s) => {
                let (idx, len) = self.add_string(s);
                let ptr = self.next_value();
                self.body.push_str(&format!(
                    "  {} = getelementptr [{} x i8], [{} x i8]* @.str.{}, i64 0, i64 0\n",
                    ptr, len, len, idx
                ));
                let as_int = self.next_value();
                self.body.push_str(&format!(
                    "  {} = ptrtoint i8* {} to i64\n",
                    as_int, ptr
                ));
                as_int
            }

            Expression::TemplateString { parts } => {
                use crate::ast::{FormatType, TemplateStringPart};

                let buf = self.next_value();
                self.body.push_str(&format!(
                    "  {} = alloca [1024 x i8], align 1\n",
                    buf
                ));
                let buf_ptr = self.next_value();
                self.body.push_str(&format!(
                    "  {} = getelementptr [1024 x i8], [1024 x i8]* {}, i64 0, i64 0\n",
                    buf_ptr, buf
                ));
                self.body.push_str(&format!(
                    "  store i8 0, i8* {}, align 1\n",
                    buf_ptr
                ));

                let tmp_buf = self.next_value();
                self.body.push_str(&format!(
                    "  {} = alloca [256 x i8], align 1\n",
                    tmp_buf
                ));
                let tmp_ptr = self.next_value();
                self.body.push_str(&format!(
                    "  {} = getelementptr [256 x i8], [256 x i8]* {}, i64 0, i64 0\n",
                    tmp_ptr, tmp_buf
                ));

                for part in parts {
                    match part {
                        TemplateStringPart::Literal(lit) => {
                            let (idx, len) = self.add_string(lit);
                            let lit_ptr = self.next_value();
                            self.body.push_str(&format!(
                                "  {} = getelementptr [{} x i8], [{} x i8]* @.str.{}, i64 0, i64 0\n",
                                lit_ptr, len, len, idx
                            ));
                            let r = self.next_value();
                            self.body.push_str(&format!(
                                "  {} = call i8* @strcat(i8* {}, i8* {})\n",
                                r, buf_ptr, lit_ptr
                            ));
                        }
                        TemplateStringPart::Expression { expr, format } => {
                            let val = self.generate_expression(expr);
                            let fmt_str = if let Some(spec) = format {
                                match spec.format_type {
                                    FormatType::Hex => {
                                        if let Some(w) = spec.width {
                                            if spec.padding == '0' {
                                                format!("%0{}lx", w)
                                            } else {
                                                format!("%{}lx", w)
                                            }
                                        } else {
                                            "%lx".to_string()
                                        }
                                    }
                                    FormatType::HexUpper => {
                                        if let Some(w) = spec.width {
                                            if spec.padding == '0' {
                                                format!("%0{}lX", w)
                                            } else {
                                                format!("%{}lX", w)
                                            }
                                        } else {
                                            "%lX".to_string()
                                        }
                                    }
                                    FormatType::Decimal => {
                                        if let Some(w) = spec.width {
                                            if spec.padding == '0' {
                                                format!("%0{}ld", w)
                                            } else {
                                                format!("%{}ld", w)
                                            }
                                        } else {
                                            "%ld".to_string()
                                        }
                                    }
                                    FormatType::String => "%s".to_string(),
                                    FormatType::Auto => "%ld".to_string(),
                                }
                            } else {
                                "%ld".to_string()
                            };

                            let (fmt_idx, fmt_len) = self.add_string(&fmt_str);
                            let fmt_ptr = self.next_value();
                            self.body.push_str(&format!(
                                "  {} = getelementptr [{} x i8], [{} x i8]* @.str.{}, i64 0, i64 0\n",
                                fmt_ptr, fmt_len, fmt_len, fmt_idx
                            ));
                            let sp_r = self.next_value();
                            self.body.push_str(&format!(
                                "  {} = call i32 (i8*, i8*, ...) @sprintf(i8* {}, i8* {}, i64 {})\n",
                                sp_r, tmp_ptr, fmt_ptr, val
                            ));
                            let cat_r = self.next_value();
                            self.body.push_str(&format!(
                                "  {} = call i8* @strcat(i8* {}, i8* {})\n",
                                cat_r, buf_ptr, tmp_ptr
                            ));
                        }
                    }
                }

                let as_int = self.next_value();
                self.body.push_str(&format!(
                    "  {} = ptrtoint i8* {} to i64\n",
                    as_int, buf_ptr
                ));
                as_int
            }

            Expression::ArrayAccess { name, index } => {
                let idx = self.generate_expression(index);
                if let Some(base_ptr) = self.variables.get(name).cloned() {
                    let elem_ptr = self.next_value();
                    self.body.push_str(&format!(
                        "  {} = getelementptr i64, i64* {}, i64 {}\n",
                        elem_ptr, base_ptr, idx
                    ));
                    let val = self.next_value();
                    self.body.push_str(&format!(
                        "  {} = load i64, i64* {}, align 8\n",
                        val, elem_ptr
                    ));
                    val
                } else {
                    "0".to_string()
                }
            }

            Expression::StringIndex { string, index } => {
                let str_int = self.generate_expression(string);
                let idx = self.generate_expression(index);
                let ptr = self.next_value();
                self.body.push_str(&format!(
                    "  {} = inttoptr i64 {} to i8*\n",
                    ptr, str_int
                ));
                let elem_ptr = self.next_value();
                self.body.push_str(&format!(
                    "  {} = getelementptr i8, i8* {}, i64 {}\n",
                    elem_ptr, ptr, idx
                ));
                let byte = self.next_value();
                self.body.push_str(&format!(
                    "  {} = load i8, i8* {}, align 1\n",
                    byte, elem_ptr
                ));
                let result = self.next_value();
                self.body.push_str(&format!(
                    "  {} = zext i8 {} to i64\n",
                    result, byte
                ));
                result
            }

            Expression::AddressOf { operand } => {
                if let Expression::Identifier(name) = operand.as_ref() {
                    if let Some(ptr) = self.variables.get(name).cloned() {
                        let as_int = self.next_value();
                        self.body.push_str(&format!(
                            "  {} = ptrtoint i64* {} to i64\n",
                            as_int, ptr
                        ));
                        return as_int;
                    }
                }
                "0".to_string()
            }

            Expression::Deref { operand } => {
                let val = self.generate_expression(operand);
                let ptr = self.next_value();
                self.body.push_str(&format!(
                    "  {} = inttoptr i64 {} to i64*\n",
                    ptr, val
                ));
                let loaded = self.next_value();
                self.body.push_str(&format!(
                    "  {} = load i64, i64* {}, align 8\n",
                    loaded, ptr
                ));
                loaded
            }

            Expression::Eval { instruction: _ } => "0".to_string(),
        }
    }

    fn generate_stdio(&mut self) {
        // stdio_Println(i64) — print integer with newline
        let (fi, fl) = self.add_string("%ld\\n");
        self.body
            .push_str("define i64 @stdio_Println(i64 %p_val) {\n");
        self.body.push_str("entry:\n");
        self.body.push_str(&format!(
            "  %fmt = getelementptr [{} x i8], [{} x i8]* @.str.{}, i64 0, i64 0\n",
            fl, fl, fi
        ));
        self.body
            .push_str("  call i32 (i8*, ...) @printf(i8* %fmt, i64 %p_val)\n");
        self.body.push_str("  ret i64 0\n");
        self.body.push_str("}\n\n");

        // stdio_Print(i64) — print integer without newline
        let (fi2, fl2) = self.add_string("%ld");
        self.body
            .push_str("define i64 @stdio_Print(i64 %p_val) {\n");
        self.body.push_str("entry:\n");
        self.body.push_str(&format!(
            "  %fmt = getelementptr [{} x i8], [{} x i8]* @.str.{}, i64 0, i64 0\n",
            fl2, fl2, fi2
        ));
        self.body
            .push_str("  call i32 (i8*, ...) @printf(i8* %fmt, i64 %p_val)\n");
        self.body.push_str("  ret i64 0\n");
        self.body.push_str("}\n\n");

        // stdio_PrintStr(i64) — print string pointer
        let (fi3, fl3) = self.add_string("%s");
        self.body
            .push_str("define i64 @stdio_PrintStr(i64 %p_str) {\n");
        self.body.push_str("entry:\n");
        self.body
            .push_str("  %ptr = inttoptr i64 %p_str to i8*\n");
        self.body.push_str(&format!(
            "  %fmt = getelementptr [{} x i8], [{} x i8]* @.str.{}, i64 0, i64 0\n",
            fl3, fl3, fi3
        ));
        self.body
            .push_str("  call i32 (i8*, ...) @printf(i8* %fmt, i8* %ptr)\n");
        self.body.push_str("  ret i64 0\n");
        self.body.push_str("}\n\n");

        // stdio_PrintlnStr(i64) — print string pointer with newline
        let (fi4, fl4) = self.add_string("%s\\n");
        self.body
            .push_str("define i64 @stdio_PrintlnStr(i64 %p_str) {\n");
        self.body.push_str("entry:\n");
        self.body
            .push_str("  %ptr = inttoptr i64 %p_str to i8*\n");
        self.body.push_str(&format!(
            "  %fmt = getelementptr [{} x i8], [{} x i8]* @.str.{}, i64 0, i64 0\n",
            fl4, fl4, fi4
        ));
        self.body
            .push_str("  call i32 (i8*, ...) @printf(i8* %fmt, i8* %ptr)\n");
        self.body.push_str("  ret i64 0\n");
        self.body.push_str("}\n\n");

        // stdio_PrintChar(i64) — print single character
        self.body
            .push_str("define i64 @stdio_PrintChar(i64 %p_c) {\n");
        self.body.push_str("entry:\n");
        self.body
            .push_str("  %c = trunc i64 %p_c to i32\n");
        self.body.push_str("  call i32 @putchar(i32 %c)\n");
        self.body.push_str("  ret i64 0\n");
        self.body.push_str("}\n\n");

        // stdio_ReadInt() — read a 64-bit integer from stdin
        let (fi5, fl5) = self.add_string("%ld");
        self.body.push_str("define i64 @stdio_ReadInt() {\n");
        self.body.push_str("entry:\n");
        self.body.push_str("  %buf = alloca i64, align 8\n");
        self.body.push_str(&format!(
            "  %fmt = getelementptr [{} x i8], [{} x i8]* @.str.{}, i64 0, i64 0\n",
            fl5, fl5, fi5
        ));
        self.body
            .push_str("  call i32 (i8*, ...) @scanf(i8* %fmt, i64* %buf)\n");
        self.body
            .push_str("  %val = load i64, i64* %buf, align 8\n");
        self.body.push_str("  ret i64 %val\n");
        self.body.push_str("}\n\n");

        // stdio_ReadChar() — read a single character from stdin
        self.body.push_str("define i64 @stdio_ReadChar() {\n");
        self.body.push_str("entry:\n");
        self.body.push_str("  %c = call i32 @getchar()\n");
        self.body
            .push_str("  %ext = sext i32 %c to i64\n");
        self.body.push_str("  ret i64 %ext\n");
        self.body.push_str("}\n\n");

        // stdio_ReadLine(i64 buf_ptr, i64 size) — read a line into buffer
        self.body
            .push_str("define i64 @stdio_ReadLine(i64 %p_buf, i64 %p_size) {\n");
        self.body.push_str("entry:\n");
        self.body
            .push_str("  %buf_ptr = inttoptr i64 %p_buf to i8*\n");
        self.body
            .push_str("  %sz = trunc i64 %p_size to i32\n");
        self.body
            .push_str("  %stdin_ptr = load i8*, i8** @stdin\n");
        self.body
            .push_str("  %res = call i8* @fgets(i8* %buf_ptr, i32 %sz, i8* %stdin_ptr)\n");
        self.body
            .push_str("  %len = call i64 @strlen(i8* %buf_ptr)\n");
        self.body.push_str("  ret i64 %len\n");
        self.body.push_str("}\n\n");

        // stdio_Flush() — flush stdout
        self.body.push_str("define i64 @stdio_Flush() {\n");
        self.body.push_str("entry:\n");
        self.body.push_str("  call i32 @fflush(i8* null)\n");
        self.body.push_str("  ret i64 0\n");
        self.body.push_str("}\n\n");
    }
}

// Convert escape sequences in Agnostic strings to LLVM IR hex escapes
fn llvm_escape(s: &str) -> String {
    let mut result = String::new();
    let bytes = s.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'\\' && i + 1 < bytes.len() {
            match bytes[i + 1] {
                b'n' => {
                    result.push_str("\\0A");
                    i += 2;
                }
                b't' => {
                    result.push_str("\\09");
                    i += 2;
                }
                b'r' => {
                    result.push_str("\\0D");
                    i += 2;
                }
                b'0' => {
                    result.push_str("\\00");
                    i += 2;
                }
                b'\\' => {
                    result.push_str("\\5C");
                    i += 2;
                }
                b'"' => {
                    result.push_str("\\22");
                    i += 2;
                }
                _ => {
                    result.push(bytes[i] as char);
                    i += 1;
                }
            }
        } else if bytes[i] == b'"' {
            result.push_str("\\22");
            i += 1;
        } else {
            result.push(bytes[i] as char);
            i += 1;
        }
    }
    result
}

// Count actual bytes (after resolving escape sequences)
fn string_byte_len(s: &str) -> usize {
    let bytes = s.as_bytes();
    let mut len = 0;
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'\\' && i + 1 < bytes.len() {
            match bytes[i + 1] {
                b'n' | b't' | b'r' | b'0' | b'\\' | b'"' => {
                    len += 1;
                    i += 2;
                }
                _ => {
                    len += 1;
                    i += 1;
                }
            }
        } else {
            len += 1;
            i += 1;
        }
    }
    len
}
